import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BottomSheet Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          TESTING BOTTOM SHEET
        </h1>

        <div className={styles.grid}>
          <a href="/half-test" className={styles.card}>
            <h2>Half and fixed height (with animation) &rarr;</h2>
          </a>
        </div>
      </main>
    </div>
  )
}
